sudo: false
language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
env:
  global:
  - secure: OM2gNBCDzPBD/WzqyFtKHmWKgXbe9XDWMZ3+iQjLnLBbP4gHNGesFlvR74X1nxvQuOzCNjLBB1IfUGFdU8GxJ0OpLXPS0KsfGEyB1eHi0qR0KFI4e3xrdC165oIP92/0+DfSlryhVfEXt0JXE92k9emSdmSMdAI72INQWXkCvJ/TNi1R3Htnrxl9zoYO5+BYhmJLqsAF/mlaBcycr1VW5mS/xlaLo8p+NcMdnz/+Lr6jki15tVWDKCCvD+obqjDEBDqD0ynzDnLlq4MhgRd87SzNaKh1SGNHN1k1GlU8ci7tkIB/wCOO+KzmBugZtiQ8zYZs0LaVl2fdE6QoH9eB+u+DVMyVXd0/c0RkAoFwOtDFn4lWxcZfYWLFCbVD/EoGzT9b7q3Odn/SKFkZJC1ate1HAMYCwb9/aXPDko78F5alrI4XdqlecYEQS02nkUYQkSr7jp4GMJiR+oIrnGR0SB6xWKeFhUsn48QddAGPEqduCp0vbEVRA+1HCYwzXvnSL+GJvezYkhZzg3cmgesiNq8ocKAhXh2qL1pJ41iCjkUsIOLdXt9KEPoKvR+HxwLNotKKuw0AYiMO1v45uG8PjnXUvsvPnh0rXBMjUVB3A9ocFGOwRMk8Urk4zo6oqJx5rrG8f4mNpwsqA2kKn5EIAfffsMeHuGYYGMgXPaA7DMU=
  - FAUNA_DOMAIN=rest.faunadb.com
  - FAUNA_SCHEME=https
  - FAUNA_PORT=443
notifications:
  email: false
  slack:
    secure: LPjAiizRsFx62YvMzCTU32XMSw4ypi2x+1AWH67lVR/tz3homIeRjwDlBwlRRk0kFH8MNA9tZpfYuo/LOvScPLgSb8KAzjuaO6g12B4xJmout2xxzzDtSQ6VS6+QcEl9gdYcl32ri7wBFfsNVcLehcz7bcKX0TfZhxTAVs0LVGFPObVkMCzG6Kwdmz8Lv1m1MrpnDFEP0bBAOlvLIgSy6aX2B4Bn7CkryV8PZ8nNEd3QRlmYkskgUHDT2C429JmwJoxq5foENv52MPMLSrMRrBAHDCLSST9t+wGItYWzJQPI8fMxMb1vHXQhCmMQ1GKRsXpqIr6Gop6rtcQuVb7dXrSN6iGSR1WqKx1gpIfdRvprQLKU905jdPUjblt517YYHG4yasC9jSfNze12hMUMuKmYZluvH732/+sdIjo5yaRvEBYC5U3G4ixneugcRsyJ50gb2TWYgoKU+ESd+PWf1/tBOU4q5/ctw3hm4BiEc54qOxliiadKfGp526H68/5AidR42gbWJt7I14g4AEy6bnaReJab1Y4nvy3Dw18SrghIDETCw06CO0KTeTMk7PbqswhQ5KhmTYC0Cb1JcwV74WghgZ8LvzDYCfsGWzAUT8AZ/q6asc3hF1mEwP4Y6F+pvNmky6nuqldRhF4V8gtKYscvyenGhutSNUsPzMKw/Sc=
branches:
  only:
    - master
