sudo: false
language: scala
scala:
  - 2.12.2
jdk:
  - oraclejdk8
script:
  - sbt jacoco:cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: RNx7z4itvtYrnMEoK0tyvOswJ99W8EObq1lgiu04SEmfB+Yh/rh6BOWxTRUXFJO2d/CgUVvmW6mcAUHFzXYq0hperXdDqJjbyaagF8GcJ6NRZVz4W1KbdFU9XaMcO9fmJdf0r3bEkpPAmxIqwR5Va0dEEebb6wiRmhlyqYYAB0LarpeLd8PCLaZAUjp/4q8lZ8yewIboJbevWdPafYfm8i8iQJxKFhrnwtq4nB59iDXujWEBJoKr1pSvGv2V9H5tKydK+AYkwpJ1ceVPgQpxNepeLFNkgCzIrZzinfyAin8I+Y2oEGukFQeemATXwHGj4kJ8AilEktOiAqrxnZKU1dn2pB880A8PtRXztS+sQ3knqFOJoJlMoDz0oEKZ2Bat8sOpGJcKZ5NioYYd5cOULDkkEjq0pWeOOb58eJQbUmkX/Z1u6hvlpFtid6+95/Q/wuC1josE5Drqy1jS7hjWhIU4g2xZ5X0VRtyiBGiEAz5A841Y5v++/eqePji9GcuvR0awxKwl6ibZrDHU8Pvcgl3LL+pC76nnP1G16caUBMSTDQ8C/jpqLYU5iJvGVZx3c+3A7q65UUl102xYnBEUfk//9K/WZo17gU0XgxkYaZHA5XDF3I55ekg/cIvKUi7J+5H0PJOI6+/YxbgtoeXYGGl49KX76gGIzk6P1oRYJ7E=
  - FAUNA_DOMAIN=db.fauna.com
  - FAUNA_SCHEME=https
  - FAUNA_PORT=443
notifications:
  email: false
  slack:
    secure: LPjAiizRsFx62YvMzCTU32XMSw4ypi2x+1AWH67lVR/tz3homIeRjwDlBwlRRk0kFH8MNA9tZpfYuo/LOvScPLgSb8KAzjuaO6g12B4xJmout2xxzzDtSQ6VS6+QcEl9gdYcl32ri7wBFfsNVcLehcz7bcKX0TfZhxTAVs0LVGFPObVkMCzG6Kwdmz8Lv1m1MrpnDFEP0bBAOlvLIgSy6aX2B4Bn7CkryV8PZ8nNEd3QRlmYkskgUHDT2C429JmwJoxq5foENv52MPMLSrMRrBAHDCLSST9t+wGItYWzJQPI8fMxMb1vHXQhCmMQ1GKRsXpqIr6Gop6rtcQuVb7dXrSN6iGSR1WqKx1gpIfdRvprQLKU905jdPUjblt517YYHG4yasC9jSfNze12hMUMuKmYZluvH732/+sdIjo5yaRvEBYC5U3G4ixneugcRsyJ50gb2TWYgoKU+ESd+PWf1/tBOU4q5/ctw3hm4BiEc54qOxliiadKfGp526H68/5AidR42gbWJt7I14g4AEy6bnaReJab1Y4nvy3Dw18SrghIDETCw06CO0KTeTMk7PbqswhQ5KhmTYC0Cb1JcwV74WghgZ8LvzDYCfsGWzAUT8AZ/q6asc3hF1mEwP4Y6F+pvNmky6nuqldRhF4V8gtKYscvyenGhutSNUsPzMKw/Sc=
branches:
  only:
  - master
script:
  sbt "android:package" test

